@FieldsAreNonnullByDefault
@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package definedentity.xenon.vec;

import javax.annotation.ParametersAreNonnullByDefault;
import net.covers1624.quack.annotation.FieldsAreNonnullByDefault;
import net.covers1624.quack.annotation.MethodsReturnNonnullByDefault;
